common: &common
  docker:
    - image: circleci/node:7.10
  working_directory: ~/workspace

version: 2
jobs:
  build:
    <<: *common

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm start

      # Persist the specified paths into the workspace.
      - persist_to_workspace:
          root: ~/
          # Must be relative path from root
          paths:
            - workspace

  test:
    <<: *common

    steps:
      - attach_workspace:
          at: ~/

      - run: npm ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
