common: &common
  docker:
    - image: circleci/node:7.10
  working_directory: ~/workspace

version: 2
jobs:
  build:
    <<: *common

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm start

      # Persist the specified paths into the workspace.
      - persist_to_workspace:
          root: ~/
          # Must be relative path from root
          paths:
            - workspace

  test:
    <<: *common

    steps:
      - attach_workspace:
          at: ~/

      - run: npm run ci

  publish:
    <<: *common

    steps:
      - attach_workspace:
          at: ~/

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run: npm publish

  deploy_docs:
    <<: *common

    steps:
      - add-ssh-keys:
        fingerprints:
          - "$DEPLOY_GH_FINGERPRINTS"

      - attach_workspace:
          at: ~/

      - run: .circleci/deploy-docs.sh

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
              ignore:
                - gh-pages
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
              ignore:
                - gh-pages
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy_docs:
          requires:
            - publish
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
